# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401
from enum import Enum

class Grid:
    ROW_COUNT: int
    COLUMN_COUNT: int
    TOP: int
    BOTTOM: int
    LEFT: int
    RIGHT: int
    NEXT_POS: tuple[float, float, float]
    HOLD_POS: tuple[float, float, float]
    JIGGLE_MOVES: list[int]

    def __new__(cls) -> Grid: ...
    def move(self, x: int, y: int) -> bool:
        """Move the active tetrimino"""

    def rotate(self, angle: Turn) -> bool:
        """Rotate the active tetrimino"""

    def inplace_collision(self) -> bool:
        """Check if the active tetrimino collides with another one"""

    def update_cells(self):
        """Store the active tetrimino cubes in the cell matrix. Should only be called in the post-loop."""

    def process_completed_rows(self) -> int:
        """Check the grid for completed rows. Delete them and move down the others if possible."""

    @property
    def active_tetrimino(self) -> Tetrimino | None: ...
    @active_tetrimino.setter
    def active_tetrimino(self, tetrimino: Tetrimino) -> None: ...

class Tetrimino:
    def __new__(cls, type: TetriminoLetter, root: str, cubes: tuple[Cube, Cube, Cube, Cube]) -> Tetrimino: ...
    @property
    def root(self) -> str: ...
    @property
    def position(self) -> tuple[float, float]: ...

class TetriminoLetter(Enum):
    T = ...
    O = ...
    L = ...
    J = ...
    Z = ...
    S = ...
    I = ...

class Turn(Enum):
    Left = ...
    Right = ...

class Cube:
    def __new__(cls, name: str) -> Cube: ...
    def move(self, x: int, y: int):
        """Move the cube to the desired coordinates."""

    @property
    def name(self) -> str: ...
